### ISSUE TITLE
What are the prerequisites for developing this project?

### ISSUE THREAD

**Issue by gbakeman** [smartboyathome/Haxxit#17]
I would really like to contribute to this project, although I'm not quite sure how to get started. I've downloaded it, I've installed Visual Studio 2010, and I've installed Monogame 3.0.1 plus the templates for VS2010. However, when I open the haxxit solution, visual studio tells me that the contentproj file type is not supported. Is Monogame 3.0.1 not backwards compatible with 3.0 (which I found out was the current project version after opening Haxxit.MonoGame.ContentBuilder.csproj in a text editor)?

**Comment by gbakeman** [comment]
https://github.com/mono/MonoGame/wiki/Tutorials%3Agettingstarted

Looks like I need XNA Game Studio 4.0.

**Comment by gbakeman** [comment]
I'd also like to mention in case anyone else is having any issues, apparently the Windows Phone SDK 7.1.1 is also a prerequisite for compiling the content pipeline.

https://github.com/mono/MonoGame/wiki/MonoGame-Content-Processing

**Comment by smartboyathome** [comment]
I apologize for not getting back quickly, I have been on vacation since the end of classes. I am also wanting to continue this project though. I am planning a refactor of SimplePubSub after I finish my vacation to fix some design flaws that would lead to rare bugs (such as events coming into a subscribed function and not being able to be sent back out).

**Comment by gbakeman** [comment]
No problem, thank you for replying even though I had closed the ticket. I loved playing Spybot: The Nightfall Incident as a kid (and I'm still having fun playing it now), so I'm really happy to see a project that might loosely recreate it. I've been exploring the code for a bit, getting an idea of what everything is for (SimplePubSub is a mysterious one for me). Unfortunately the Windows Phone SDK is a deal breaker for me right now in terms of contributing; I can't blow my phones data allotment over that ~200 something MB download :\ I do hope to contribute soon though! Would you mind if I made a wiki page with a few pointers for getting started (that I've learned so far, such as what to download/install)?

**Comment by smartboyathome** [comment]
When I get back from my vacation, I most definitely will! Also, this isn't made to be on Windows Phone, the only reason it needs the SDK is because XNA (and thus, MonoGame) requires it to build the *.xnb files for content. The MonoGame community is hard at work right now building an alternative to this since the XNA SDKs aren't going to be supported forever due to Microsoft discontinuing XNA. I apologize for the difficulties in getting it set up though. :(

**Comment by smartboyathome** [comment]
Oh, and as far as SimplePubSub goes, you might want to look up Publish/Subscribe to understand it. To put it simply, it is a loosely coupled event system, as opposed to Microsoft's tightly coupled event system that is included by default in C#.

**Comment by gbakeman** [comment]
Thanks, I think I will look that up. I honestly feel like I'll never learn everything there is to know about C# :p It is a bummer that you need the Phone SDK even if you won't develop for it. Hope your vacation is/was a good one.

**Comment by smartboyathome** [comment]
We do have binaries available at http://courses.washington.edu/css385/2013.Spring/FinalProjects/index.html if you just want to play it. It shouldn't require the Phone SDK to run. However, you may have to install OpenAL (from http://connect.creativelabs.com/openal/default.aspx ) to run it.

**Comment by gbakeman** [comment]
Ah, cool! I tried to download it, but the website said the requested resource was unavailable :(
